# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: max@maxherbert.com
author_name: Max Herbert
description: IOC for the Hive Control Unit
distribution_name: hive-controller-ioc
docker: true
docs_type: README
git_platform: github.com
github_org: buzz-metrics
package_name: hive_controller_ioc
pypi: false
repo_name: hive_controller_ioc
type_checker: pyright
